### ISSUE TITLE
Stream threads crashing with Topic not found during partition assignment: android_empatica_e4_acceleration

### ISSUE THREAD

**Issue by nivemaham** [RADAR-CNS/RADAR-Backend#14]
I frequently get  following exception for some of the streams when radar-backend-stream is initialized.
 ```
[08:54:33] INFO  StreamThread-1 org.apache.kafka.streams.processor.internals.StreamThread.shutdown:292 - stream-thread [StreamThread-1] Stream thread shutdown complete
radar-backend-stream_1     | [08:54:33] ERROR StreamThread-1 org.radarcns.stream.aggregator.AggregatorWorker.uncaughtException:118 - Thread StreamThread-1 has been terminated due to Topic not found during partition assignment: android_empatica_e4_acceleration
radar-backend-stream_1     | org.apache.kafka.streams.errors.StreamsException: Topic not found during partition assignment: android_empatica_e4_acceleration
radar-backend-stream_1     | 	at org.apache.kafka.streams.processor.DefaultPartitionGrouper.maxNumPartitions(DefaultPartitionGrouper.java:81)
radar-backend-stream_1     | 	at org.apache.kafka.streams.processor.DefaultPartitionGrouper.partitionGroups(DefaultPartitionGrouper.java:55)
radar-backend-stream_1     | 	at org.apache.kafka.streams.processor.internals.StreamPartitionAssignor.assign(StreamPartitionAssignor.java:370)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.performAssignment(ConsumerCoordinator.java:313)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.onJoinLeader(AbstractCoordinator.java:467)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.access$1000(AbstractCoordinator.java:88)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:419)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$JoinGroupResponseHandler.handle(AbstractCoordinator.java:395)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:742)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$CoordinatorResponseHandler.onSuccess(AbstractCoordinator.java:722)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.RequestFuture$1.onSuccess(RequestFuture.java:186)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.RequestFuture.fireSuccess(RequestFuture.java:149)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.RequestFuture.complete(RequestFuture.java:116)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient$RequestFutureCompletionHandler.fireCompletion(ConsumerNetworkClient.java:479)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.firePendingCompletedRequests(ConsumerNetworkClient.java:316)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:256)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:180)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:308)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:277)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:259)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1013)
radar-backend-stream_1     | 	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979)
radar-backend-stream_1     | 	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:407)
radar-backend-stream_1     | 	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:242)
radar-backend-stream_1     | [08:54:33] WARN  StreamThread-1 org.radarcns.stream.aggregator.MasterAggregator.notifyCrashedStream:148 - [Empatica E4] E4Acceleration is crashed
```
Once the streams are crashed the threads are not recovered. It is not specific for particular topic(s).
 
Steps to reproduce:
1) Initialize the radar-backend . ( I used [docker-compose](https://github.com/RADAR-CNS/RADAR-Backend/blob/dev/docker/docker-compose.yml) ) 
2) Follow the logs for radar-backend-stream

**Comment by nivemaham** [comment]
This [issue](https://issues.apache.org/jira/browse/KAFKA-4355) appears to be related to what we are having.

**Comment by blootsvoets** [comment]
I'm refactoring the MasterAggregator to restart streams.

**Comment by fnobilia** [comment]
Fixed by
- RADAR-CNS/RADAR-Backend@416ee28
- RADAR-CNS/RADAR-Docker@09a8798
Now, all backend components wait instantiations of all required topics for starting.
