### ISSUE TITLE
One of the monitors fails to start

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-CNS/RADAR-Backend#35]
One of the `BatteryLevelMonitor.java` or `DisconnectMonitor` fail to start when we want to start both together as both have the same client id. 
Logs attached - 

```
[2017-11-03 17:03:59 GMT]  INFO [pool-2-thread-1] (AppInfoParser.java:83) - Kafka version : 0.11.0.1 (org.apache.kafka.common.utils.AppInfoParser)
[2017-11-03 17:03:59 GMT]  INFO [pool-2-thread-1] (AppInfoParser.java:84) - Kafka commitId : c2a0d5f9b1f45bf5 (org.apache.kafka.common.utils.AppInfoParser)
[2017-11-03 17:03:59 GMT]  INFO [pool-2-thread-2] (AbstractKafkaMonitor.java:155) - Monitoring streams [android_empatica_e4_battery_level] (org.radarcns.monitor.AbstractKafkaMonitor)
[2017-11-03 17:03:59 GMT]  WARN [pool-2-thread-1] (AppInfoParser.java:60) - Error registering AppInfo mbean (org.apache.kafka.common.utils.AppInfoParser)
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=1
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:58)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:757)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:633)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:615)
	at org.radarcns.monitor.AbstractKafkaMonitor.start(AbstractKafkaMonitor.java:152)
	at org.radarcns.monitor.CombinedKafkaMonitor.lambda$start$0(CombinedKafkaMonitor.java:78)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yatharthranjan** [comment]
closed by #36
